services:
  #Database
  westridge_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3333:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: westridge_db
  #Web
  westridge_wp:
    depends_on:
      - westridge_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8095:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: westridge_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: westridge_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  westridge_myadmin:
    image: phpmyadmin:latest
    container_name: westridge_myadmin
    restart: "no"
    ports:
      - 5015:80
    environment:
      PMA_HOST: westridge_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - westridge_db
volumes:
  db_data:
  wp-content:
